export const FETCH_ALL_SUBSCRIPTIONS = "FETCH_ALL_SUBSCRIPTIONS";
export const FETCH_SUBSCRIPTION_BY_ID = "FETCH_SUBSCRIPTION_BY_ID";
export const FETCH_PARTICULAR_SUBSCRIPTION_BY_FREELANCER = "FETCH_PARTICULAR_SUBSCRIPTION_BY_FREELANCER";
export const FETCH_PROFESSIONNAL_SUBSCRIPTION_BY_FREELANCER = "FETCH_PROFESSIONNAL_SUBSCRIPTION_BY_FREELANCER";
